function ydot = Rate_pt(t, y, ...
                         C, ...
                         apt, ... 
                         u_norm)

ydot    = zeros(length(y),1);
ydot    = apt*u_norm.*C;           % Pore throat dep. rate
